# Generated by Django 5.0.6 on 2024-10-03 14:19

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_date_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovemessage',
            name='scheduled_date',
            field=models.DateField(verbose_name=main_app.models.Schedule),
        ),
    ]
